site_name: 'bread-test'
site_url: https://github.com/tadamhicks/bread-test

docs_dir: docs

nav:
  - Home: README.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
