apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-load-test
  namespace: books
  labels:
    app: k6-load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-load-test
  template:
    metadata:
      labels:
        app: k6-load-test
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["/bin/sh", "/runner/run.sh"]
          env:
            - name: K6_OUT
              value: experimental-prometheus-rw
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: https://example.platform-dev.grcv.io:443/api/v1/write
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: 1s
            - name: K6_PROMETHEUS_RW_INSECURE_SKIP_TLS_VERIFY
              value: "true"
            - name: K6_PROMETHEUS_RW_HTTP_HEADERS
              value: "apikey:${apikey}"
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: "avg,p(90),p(95),min,max"
            - name: K6_PROMETHEUS_RW_METRIC_PUSH_CONSTANT_LABELS
              value: "source=k6,env=demo,service=k6-load-test"
            - name: K6_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: k6-test
              mountPath: /tests
            - name: k6-runner-script
              mountPath: /runner
      volumes:
        - name: k6-test
          configMap:
            name: k6-test
        - name: k6-runner-script
          configMap:
            name: k6-runner-script
            defaultMode: 0775