apiVersion: v1
kind: Service
metadata:
  name: k6-load-test
  namespace: books
  labels:
    app: k6-load-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6565"
spec:
  selector:
    app: k6-load-test
  ports:
    - protocol: TCP
      port: 6565
      targetPort: 6565
