apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1000

      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
        spike_limit_mib: 200

      resource:
        attributes:
          - key: service.name
            value: "bookapi"
            action: insert
          - key: deployment.environment
            value: "dev"
            action: insert
          - key: deployment.version
            value: "1.0.0"
            action: insert

    connectors:
    exporters:
    service:
      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
      pipelines:
        traces:
          receivers: []
          processors: [batch, memory_limiter, resource]
          exporters: []

        metrics:
          receivers: []
          processors: [resource, batch]
          exporters: []

        metrics/statsd:
          receivers: []
          processors: [resource, batch]
          exporters: []
