apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: books
data:
  otel-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
        send_batch_max_size: 2048

      memory_limiter:
        check_interval: 1s
        limit_mib: 128



    exporters:
      # Groundcover inCloud Managed - HTTP endpoints
      otlphttp/groundcover:
        endpoint: https://example.platform-dev.grcv.io
        headers: 
          apikey: "${apikey}"
        tls:
          insecure: false

      # Optional: Keep debug exporter for debugging
      debug:
        verbosity: normal

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/groundcover, debug]

        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/groundcover, debug]

        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/groundcover, debug]

      telemetry:
        logs:
          level: debug