apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      datadog:
        endpoint: 0.0.0.0:8126
      statsd:
        endpoint: 0.0.0.0:8125
        aggregation_interval: 10s
        enable_metric_type: true

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1000

      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
        spike_limit_mib: 200

      resource:
        attributes:
          - key: service.name
            value: bookapi
            action: insert
          - key: deployment.environment
            value: dev
            action: insert
          - key: deployment.version
            value: 1.0.0
            action: insert

    connectors:
      datadog/connector:
        traces:
          # Filter out any spans that should not count toward metrics (optional)
          ignore_resources: [ "(GET|POST) /healthcheck", "(GET|POST) /probe" ]

    exporters:
      datadog/exporter:
        api:
          key: ${DD_API_KEY}
          site: datadoghq.com

    service:
      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
      pipelines:
        traces:
          receivers: [datadog]
          processors: [batch, resource]
          exporters: [datadog/connector, datadog/exporter]

        metrics:
          receivers: [datadog/connector]
          processors: [batch]
          exporters: [datadog/exporter]

        metrics/statsd:
          receivers: [statsd]
          processors: [batch]
          exporters: [datadog/exporter]
